---
application:
  name: "flow-heater"
  project: "flow-heater"
  organization: "QoveryCommunity"
routers:
- name: "main-flow-heater"
  routes:
  - application_name: "flow-heater"
    paths:
    - "/*"
